# Generated by Django 3.2.3 on 2021-05-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000, verbose_name='ファイルパス')),
            ],
        ),
        migrations.CreateModel(
            name='ImageListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイルパス')),
                ('image_data', models.ImageField(upload_to='images/', verbose_name='画像データ')),
                ('imageList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagelist.imagelist')),
            ],
        ),
        migrations.DeleteModel(
            name='SuzuImage',
        ),
    ]
