# Generated by Django 3.2.3 on 2021-05-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0002_auto_20210530_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='file_name',
            field=models.CharField(default='hoge', max_length=100, verbose_name='ファイル名'),
            preserve_default=False,
        ),
    ]
