# Generated by Django 3.2.3 on 2021-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0003_imagelist_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelistdetail',
            name='order_no',
            field=models.IntegerField(default=1, verbose_name='表示順'),
            preserve_default=False,
        ),
    ]
