# Generated by Django 3.2.3 on 2021-06-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0004_imagelistdetail_order_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagelistdetail',
            old_name='order_no',
            new_name='disp_order',
        ),
    ]
